### ISSUE TITLE
Installing instructions

### ISSUE THREAD

**Issue by scohe001** [M-Evans/bashAutotest#2]
Was trying to use this for HW2 when I realized that we need to use `sudo`, which is not possible while we're ssh-ed into hammer.

**Comment by M-Evans** [comment]
Change the install directory in the makefile to `$(HOME)/bin` when installing in hammer.

**Comment by M-Evans** [comment]
For personal use only, that is. Make sure you have `~/bin` in your `$PATH` (`echo $PATH`) and that `~/bin` exists (`[ -d ~/bin ] && echo success || echo fail`) before proceeding.
